# Generated by Django 4.1.3 on 2022-11-29 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birth_date',
        ),
    ]
