# Generated by Django 4.1.3 on 2022-11-14 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('relationPlayground', '0002_toppings_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desig', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('societies', models.ManyToManyField(through='relationPlayground.Membership', to='relationPlayground.society')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationPlayground.person'),
        ),
        migrations.AddField(
            model_name='membership',
            name='societyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relationPlayground.society'),
        ),
    ]
