# Generated by Django 4.1.3 on 2022-11-14 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_phoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True, validators=[django.core.validators.EmailValidator(message='Email Address is not valid')]),
        ),
    ]
